-- 数据库初始化脚本
-- 创建数据库
CREATE DATABASE db_blog;
-- 使用数据库
use db_blog;

DROP TABLE IF EXISTS t_blogger;
CREATE TABLE t_blogger (
  id INT(11) NOT NULL AUTO_INCREMENT,
  userName VARCHAR(50) DEFAULT NULL,
  PASSWORD VARCHAR(100) DEFAULT NULL,
  PROFILE TEXT,
  nickName VARCHAR(50) DEFAULT NULL,
  SIGN VARCHAR(100) DEFAULT NULL,
  imageName VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;